name: Deploy API to VDS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to VDS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        password: ${{ secrets.VDS_PASSWORD }}
        script: |
          # Navigate to applications directory
          cd /opt/applications/
          
          # Clone or pull repository
          if [ -d "clerk-token-validation-api" ]; then
            cd clerk-token-validation-api
            git pull origin main
          else
            git clone https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git clerk-token-validation-api
            cd clerk-token-validation-api
          fi
          
          # Stop and remove existing container
          docker stop clerk-token-validation-api || true
          docker rm clerk-token-validation-api || true
          docker rmi clerk-token-validation-api || true
          
          # Build new image
          docker build -t clerk-token-validation-api .
          
          # Run new container
          docker run -d \
            --name clerk-token-validation-api \
            --network nginx-network \
            -p 8002:3000 \
            --restart always \
            -e PORT=3000 \
            -e NODE_ENV=production \
            -e CLERK_SECRET_KEY="${{ secrets.CLERK_SECRET_KEY }}" \
            clerk-token-validation-api
          
          echo "Deployment completed successfully!"
